name: Sync to Public Repo

on:
  push:
    branches:
      - openSource

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: openSource

      - name: Push to public repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT_TOKEN }}
        with:
          source-directory: "."
          destination-github-username: "Rifatul-Islam-Munna"
          destination-repository-name: "open-source-pharmacy-management-software"
          target-branch: main
